"""
Tests for narrative validation in _salvar_resultado().

UPDATED 2026-02-27: The old narrative field validation (F8-T5) was removed
as part of the Two-Pass Pipeline migration. Stages no longer require
narrativa_correcao/narrativa_habilidades/relatorio_narrativo fields in JSON.
Instead, narrative content is generated by Pass 2 (separate internal prompt)
and converted directly to PDF.

These tests now verify that the OLD validation is REMOVED and stages accept
JSON without narrative fields.

Related: Fix Narrative Pipeline — Merge Rich Narratives into Existing PDFs
"""

import pytest
from unittest.mock import MagicMock


@pytest.fixture
def executor_com_mock_storage():
    """PipelineExecutor with mocked storage for validation tests."""
    from executor import PipelineExecutor
    executor = PipelineExecutor.__new__(PipelineExecutor)
    executor.storage = MagicMock()
    executor.prompt_manager = MagicMock()
    executor.preparador = None

    doc = MagicMock()
    doc.id = "doc-test-001"
    executor.storage.salvar_documento.return_value = doc
    executor.storage.listar_documentos.return_value = []

    return executor


class TestNarrativaValidationRemoved:
    """
    Post Two-Pass Pipeline: stages must NOT raise ValueError for missing
    narrative fields. The narrative is now generated in a separate LLM pass.
    """

    async def test_corrigir_accepts_json_without_narrativa_correcao(
        self, executor_com_mock_storage
    ):
        """CORRIGIR must accept JSON without narrativa_correcao field."""
        from prompts import EtapaProcessamento

        resposta = {"nota": 7.5, "questoes": [{"numero": 1}]}

        result = await executor_com_mock_storage._salvar_resultado(
            etapa=EtapaProcessamento.CORRIGIR,
            atividade_id="ativ-001",
            aluno_id="aluno-001",
            resposta_raw='{"nota": 7.5}',
            resposta_parsed=resposta,
            provider="openai", modelo="gpt-4o",
            prompt_id="default_corrigir",
            tokens=1500, tempo_ms=3000.0,
            gerar_formatos_extras=False,
        )
        assert result is not None

    async def test_analisar_habilidades_accepts_json_without_narrativa(
        self, executor_com_mock_storage
    ):
        """ANALISAR_HABILIDADES must accept JSON without narrativa_habilidades."""
        from prompts import EtapaProcessamento

        resposta = {"habilidades": {"dominadas": ["X"]}}

        result = await executor_com_mock_storage._salvar_resultado(
            etapa=EtapaProcessamento.ANALISAR_HABILIDADES,
            atividade_id="ativ-001",
            aluno_id="aluno-001",
            resposta_raw='{}',
            resposta_parsed=resposta,
            provider="openai", modelo="gpt-4o",
            prompt_id="default_analisar_habilidades",
            tokens=1200, tempo_ms=2500.0,
            gerar_formatos_extras=False,
        )
        assert result is not None

    async def test_gerar_relatorio_accepts_json_without_relatorio_narrativo(
        self, executor_com_mock_storage
    ):
        """GERAR_RELATORIO must accept JSON without relatorio_narrativo."""
        from prompts import EtapaProcessamento

        resposta = {"nota_final": 7.5, "resumo": "OK"}

        result = await executor_com_mock_storage._salvar_resultado(
            etapa=EtapaProcessamento.GERAR_RELATORIO,
            atividade_id="ativ-001",
            aluno_id="aluno-001",
            resposta_raw='{}',
            resposta_parsed=resposta,
            provider="openai", modelo="gpt-4o",
            prompt_id="default_gerar_relatorio",
            tokens=2000, tempo_ms=4000.0,
            gerar_formatos_extras=False,
        )
        assert result is not None

    async def test_extrair_questoes_nao_afetado(self, executor_com_mock_storage):
        """EXTRAIR_QUESTOES still works as before — no narrative logic."""
        from prompts import EtapaProcessamento

        resposta = {"questoes": [{"numero": 1, "enunciado": "Teste?"}]}

        result = await executor_com_mock_storage._salvar_resultado(
            etapa=EtapaProcessamento.EXTRAIR_QUESTOES,
            atividade_id="ativ-001",
            aluno_id="aluno-001",
            resposta_raw='{}',
            resposta_parsed=resposta,
            provider="openai", modelo="gpt-4o",
            prompt_id="default_extrair_questoes",
            tokens=500, tempo_ms=1000.0,
            gerar_formatos_extras=False,
        )
        assert result is not None
