"""
Test creating a detailed student report PDF via tool use
"""

import asyncio
import os
import sys
from dotenv import load_dotenv

load_dotenv()

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')


async def test_student_report_pdf():
    """Test creating a detailed student report PDF."""
    from chat_service import ChatClient, ModelConfig, ProviderType, api_key_manager
    from tools import create_registry_with_handlers, ToolExecutionContext

    model_config = ModelConfig(
        id="test-haiku",
        nome="Claude Haiku Test",
        modelo="claude-haiku-4-5-20251001",
        tipo=ProviderType.ANTHROPIC,
        max_tokens=4096,
        suporta_temperature=True,
        temperature=0.5
    )

    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        key_config = api_key_manager.get_por_empresa(ProviderType.ANTHROPIC)
        if key_config:
            api_key = key_config.api_key

    if not api_key:
        print("ERROR: No Anthropic API key found!")
        return

    client = ChatClient(model_config, api_key)
    tool_registry = create_registry_with_handlers(["execute_python_code"])
    tools = tool_registry.get_anthropic_tools()

    print("=" * 60)
    print("STUDENT REPORT PDF TEST")
    print("=" * 60)

    message = """
    Create a professional student report PDF called 'student_report.pdf' using reportlab.

    The report should include:

    1. A header with the school name "Escola Internacional ABC" and today's date

    2. Student information:
       - Name: Vinícius Soares Martins
       - Subject: Inglês (English)
       - Activity: Test 1 - Verb Tenses
       - Class: 9º Ano B

    3. A grades table with these columns:
       | Question | Topic | Score | Max Score |
       |----------|-------|-------|-----------|
       | Q1 | Present Simple | 8 | 10 |
       | Q2 | Past Simple | 7 | 10 |
       | Q3 | Future Will | 9 | 10 |
       | Q4 | Present Perfect | 6 | 10 |
       | Total | - | 30 | 40 |

    4. A feedback section with the text:
       "Vinícius demonstrated good understanding of verb tenses overall.
        Areas for improvement: Present Perfect tense usage needs more practice.
        Recommendation: Review irregular past participles."

    5. A footer with "Generated by Prova AI System"

    Use professional styling with colors (blue header, alternating row colors in table).
    """

    print(f"Request: Create detailed student report PDF\n")
    print("-" * 60)

    context = ToolExecutionContext()

    try:
        response = await client.chat_with_tools(
            mensagem=message,
            tools=tools,
            tool_registry=tool_registry,
            context=context,
            max_iterations=5
        )

        print(f"\nResponse:\n{response.get('content', '')}\n")

        if response.get("tool_calls"):
            print("-" * 60)
            print(f"Tool calls: {len(response['tool_calls'])}")
            for tc in response["tool_calls"]:
                print(f"\nTool: {tc['name']}")
                code = tc.get('input', {}).get('code', '')
                print(f"Code length: {len(code)} chars")
                # Show first 500 chars of code
                print(f"Code preview:\n{code[:500]}...")

        print(f"\nTokens: {response.get('tokens', 0)}")

    except Exception as e:
        print(f"ERROR: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    asyncio.run(test_student_report_pdf())
