"""
Testes para schemas narrativos dos stages analíticos do pipeline.

UPDATED 2026-02-27: With the Two-Pass Pipeline migration, narrative fields
(narrativa_correcao, narrativa_habilidades, relatorio_narrativo) are no longer
part of the Pass 1 JSON prompts. Instead, they are generated by internal
narrative prompts in Pass 2. The Pydantic schemas still support these fields
for backwards compatibility, but the prompts no longer request them.

Related: Fix Narrative Pipeline — Merge Rich Narratives into Existing PDFs
Original tasks: F3-T1, F4-T1, F5-T1
"""

import pytest


# ============================================================
# F3-T1 — CORRIGIR: schema still supports narrativa_correcao
# ============================================================

class TestCorrecaoQuestaoNarrativa:
    """Schema CorrecaoQuestao still supports narrativa_correcao for backwards compat."""

    def test_correcao_questao_schema_tem_campo_narrativa_correcao(self):
        """Schema do CorrecaoQuestao deve ter o campo narrativa_correcao."""
        from pipeline_validation import obter_schema_json

        schema = obter_schema_json("corrigir")
        assert schema is not None, "Schema do stage 'corrigir' não encontrado"
        assert "narrativa_correcao" in schema["properties"], (
            "Campo 'narrativa_correcao' ausente no schema de CorrecaoQuestao."
        )

    def test_correcao_questao_preserva_narrativa_nao_vazia(self):
        """CorrecaoQuestao deve aceitar e preservar narrativa_correcao não-vazia."""
        from pipeline_validation import CorrecaoQuestao

        narrativa_exemplo = (
            "## Questão 1 — Análise\n\n"
            "**O que o aluno tentou fazer:** Aplicou lei de Boyle corretamente "
            "mas confundiu unidade de pressão, usando atm em vez de Pa.\n\n"
            "**Tipo de erro:** Erro de unidade/conversão.\n\n"
            "**Potencial:** Alto."
        )

        correcao = CorrecaoQuestao(
            nota=0.5, nota_maxima=1.0, percentual=50,
            status="parcial", feedback="Erro de unidade.",
            narrativa_correcao=narrativa_exemplo,
        )
        assert correcao.narrativa_correcao is not None
        assert len(correcao.narrativa_correcao) > 50

    def test_narrative_handled_by_internal_prompt_not_pass1(self):
        """Narrative generation is now in internal Pass 2 prompts, not Pass 1."""
        from prompts import PROMPTS_NARRATIVA_INTERNA

        prompt = PROMPTS_NARRATIVA_INTERNA.get("internal_narrativa_corrigir")
        assert prompt is not None, "Internal narrative prompt for CORRIGIR must exist"
        assert "Análise" in prompt["texto"] or "análise" in prompt["texto"], (
            "Internal narrative prompt must contain analysis instructions"
        )


# ============================================================
# F4-T1 — ANALISAR_HABILIDADES: schema still supports narrativa_habilidades
# ============================================================

class TestAnaliseHabilidadesNarrativa:
    """Schema AnaliseHabilidades still supports narrativa_habilidades for backwards compat."""

    def test_analise_habilidades_schema_tem_campo_narrativa_habilidades(self):
        """Schema do AnaliseHabilidades deve ter o campo narrativa_habilidades."""
        from pipeline_validation import obter_schema_json

        schema = obter_schema_json("analisar_habilidades")
        assert schema is not None
        assert "narrativa_habilidades" in schema["properties"]

    def test_analise_habilidades_preserva_narrativa_nao_vazia(self):
        """AnaliseHabilidades deve aceitar e preservar narrativa_habilidades não-vazia."""
        from pipeline_validation import AnaliseHabilidades

        narrativa_exemplo = (
            "## Perfil de Aprendizado — João\n\n"
            "**Consistência:** Erros consistentes em conversão de unidades. "
            "Em 4 das 6 questões, demonstra método correto mas erra unidade.\n\n"
            "**Esforço vs. Conhecimento:** Questões em branco são de astronomia. "
            "João respondeu todas de biologia mesmo parcialmente."
        )

        analise = AnaliseHabilidades(
            aluno="João Silva",
            resumo_desempenho="Bom desempenho com erros de unidade.",
            nota_final=7.5, nota_maxima=10.0, percentual_acerto=75,
            habilidades={
                "dominadas": [{"nome": "Lei de Boyle", "evidencia": "Q1, Q3"}],
                "em_desenvolvimento": [{"nome": "Conversão", "evidencia": "Q2, Q4"}],
                "nao_demonstradas": [{"nome": "Astronomia", "evidencia": "Q8, Q9"}],
            },
            narrativa_habilidades=narrativa_exemplo,
        )
        assert analise.narrativa_habilidades is not None
        assert len(analise.narrativa_habilidades) > 100

    def test_narrative_handled_by_internal_prompt_not_pass1(self):
        """Narrative generation is now in internal Pass 2 prompts, not Pass 1."""
        from prompts import PROMPTS_NARRATIVA_INTERNA

        prompt = PROMPTS_NARRATIVA_INTERNA.get("internal_narrativa_analisar_habilidades")
        assert prompt is not None, "Internal narrative prompt for ANALISAR_HABILIDADES must exist"
        assert "padrão" in prompt["texto"].lower() or "padrões" in prompt["texto"].lower(), (
            "Internal narrative prompt must contain pattern analysis instructions"
        )


# ============================================================
# F5-T1 — GERAR_RELATORIO: schema still supports relatorio_narrativo
# ============================================================

class TestRelatorioFinalNarrativa:
    """Schema RelatorioFinal still supports relatorio_narrativo for backwards compat."""

    def test_relatorio_final_schema_tem_campo_relatorio_narrativo(self):
        """Schema do RelatorioFinal deve ter o campo relatorio_narrativo."""
        from pipeline_validation import obter_schema_json

        schema = obter_schema_json("gerar_relatorio")
        assert schema is not None
        assert "relatorio_narrativo" in schema["properties"]

    def test_relatorio_narrativo_contem_secao_visao_geral(self):
        """relatorio_narrativo deve aceitar conteúdo com seção de visão geral."""
        from pipeline_validation import RelatorioFinal

        relatorio_narrativo = (
            "## Visão Geral\n\nJoão demonstrou bom domínio de Física com 75%.\n\n"
            "## Análise por Questão\n\nMecânica: correto. Astronomia: em branco.\n\n"
            "## Recomendações\n\nFoco em conversão de unidades."
        )

        relatorio = RelatorioFinal(
            conteudo="# Relatório\n\nConteúdo.", resumo_executivo="75%.",
            nota_final="7.5", aluno="João", materia="Física", atividade="Prova 1",
            relatorio_narrativo=relatorio_narrativo,
        )
        assert relatorio.relatorio_narrativo is not None
        assert "Visão Geral" in relatorio.relatorio_narrativo

    def test_narrative_handled_by_internal_prompt_not_pass1(self):
        """Narrative generation is now in internal Pass 2 prompts, not Pass 1."""
        from prompts import PROMPTS_NARRATIVA_INTERNA

        prompt = PROMPTS_NARRATIVA_INTERNA.get("internal_narrativa_gerar_relatorio")
        assert prompt is not None, "Internal narrative prompt for GERAR_RELATORIO must exist"
        assert "Visão Geral" in prompt["texto"], (
            "Internal narrative prompt must contain Visão Geral section"
        )
