"""
Integration tests for F6-T3: routes_pipeline.py document conversion endpoint must
produce documents with auto-generated display_names.

When POST /api/documentos/{id}/regenerar/{formato} creates a new document from
an existing JSON document, the new document must have a proper display_name
auto-generated by salvar_documento() — not blank, not a temp path.

Since F3-T1 already wired salvar_documento() to auto-generate display_name from
atividade_id/aluno_id metadata, this test pins the contract for the conversion
endpoint specifically.

Plan: docs/PLAN_File_Naming_Document_Tracking.md  (F6-T3)
"""
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

import json
import pytest
from pathlib import Path
from fastapi.testclient import TestClient


# ============================================================
# F6-T3 Tests
# ============================================================

class TestPipelineConversionDisplayName:
    """
    POST /api/documentos/{id}/regenerar/{formato} must create a new document
    whose display_name is auto-generated from the source document's metadata.
    """

    @pytest.fixture(autouse=True)
    def setup(self, monkeypatch, temp_data_dir):
        """Set up isolated SQLite-backed storage with a pre-existing JSON document.

        Creates the full hierarchy + saves a JSON CORRECAO document so that the
        conversion endpoint has something to convert.
        """
        monkeypatch.setattr("storage.SUPABASE_DB_AVAILABLE", False)
        monkeypatch.setattr("storage.SUPABASE_STORAGE_AVAILABLE", False)

        from storage import StorageManager
        from models import TipoDocumento

        self.storage = StorageManager(base_path=str(temp_data_dir))

        self.materia = self.storage.criar_materia(nome="Física")
        self.turma = self.storage.criar_turma(
            materia_id=self.materia.id, nome="Turma B"
        )
        self.atividade = self.storage.criar_atividade(
            turma_id=self.turma.id, nome="Prova 2"
        )
        self.aluno = self.storage.criar_aluno(
            nome="João Santos", matricula="2024002"
        )
        self.storage.vincular_aluno_turma(
            aluno_id=self.aluno.id, turma_id=self.turma.id
        )

        # Create a JSON source document to convert
        json_content = json.dumps({
            "nota": 7.5,
            "questoes": [
                {"numero": 1, "nota": 3.5, "feedback": "Bom"},
                {"numero": 2, "nota": 4.0, "feedback": "Excelente"},
            ],
            "observacoes": "Trabalho consistente",
        })
        json_file = temp_data_dir / "source_correcao.json"
        json_file.write_text(json_content, encoding="utf-8")

        self.source_doc = self.storage.salvar_documento(
            arquivo_origem=str(json_file),
            tipo=TipoDocumento.CORRECAO,
            atividade_id=self.atividade.id,
            aluno_id=self.aluno.id,
            criado_por="sistema",
        )

        # Patch storage in endpoint modules
        monkeypatch.setattr("main_v2.storage", self.storage)
        monkeypatch.setattr("routes_extras.storage", self.storage)
        monkeypatch.setattr("routes_pipeline.storage", self.storage)

        from main_v2 import app
        self.client = TestClient(app)

    def test_converted_doc_has_nonempty_display_name(self):
        """
        POST /api/documentos/{id}/regenerar/csv must return a new document
        with a non-empty display_name.
        """
        response = self.client.post(
            f"/api/documentos/{self.source_doc.id}/regenerar/csv"
        )

        assert response.status_code == 200, (
            f"Expected 200, got {response.status_code}: {response.text}"
        )
        data = response.json()
        assert data["sucesso"] is True

        # Fetch the new document from storage to check display_name
        novo_doc_id = data["novo_documento"]["id"]
        docs = self.storage.listar_documentos(
            self.atividade.id, self.aluno.id
        )
        novo_doc = next((d for d in docs if d.id == novo_doc_id), None)
        assert novo_doc is not None, f"Converted doc {novo_doc_id} not found"

        assert novo_doc.display_name, (
            f"Converted document must have a non-empty display_name, "
            f"got '{novo_doc.display_name}'. salvar_documento() should "
            "auto-generate it from the atividade→turma→materia hierarchy."
        )

    def test_converted_doc_display_name_has_tipo_label(self):
        """
        The display_name of a converted CORRECAO document must contain
        the tipo label 'Correção'.
        """
        response = self.client.post(
            f"/api/documentos/{self.source_doc.id}/regenerar/csv"
        )

        assert response.status_code == 200
        data = response.json()
        novo_doc_id = data["novo_documento"]["id"]

        docs = self.storage.listar_documentos(
            self.atividade.id, self.aluno.id
        )
        novo_doc = next((d for d in docs if d.id == novo_doc_id), None)
        assert novo_doc is not None

        assert "Correção" in novo_doc.display_name or "Correcao" in novo_doc.display_name, (
            f"display_name '{novo_doc.display_name}' must contain the tipo label "
            "'Correção'. The conversion endpoint passes tipo=documento.tipo to "
            "salvar_documento(), which auto-generates via build_display_name()."
        )

    def test_converted_doc_display_name_has_aluno_materia(self):
        """
        The display_name of a converted document must include the aluno name
        ('João Santos') and materia name ('Física').
        """
        response = self.client.post(
            f"/api/documentos/{self.source_doc.id}/regenerar/csv"
        )

        assert response.status_code == 200
        data = response.json()
        novo_doc_id = data["novo_documento"]["id"]

        docs = self.storage.listar_documentos(
            self.atividade.id, self.aluno.id
        )
        novo_doc = next((d for d in docs if d.id == novo_doc_id), None)
        assert novo_doc is not None

        display = novo_doc.display_name
        assert "João Santos" in display or "Joao Santos" in display, (
            f"display_name '{display}' must contain the aluno name 'João Santos'."
        )
        assert "Física" in display or "Fisica" in display, (
            f"display_name '{display}' must contain the materia name 'Física'."
        )
